name: Firmware Upgrade
on: push
#  schedule:
#    - cron: '0 0 * * SAT'

jobs:

  job1:
    runs-on: windows-latest
    steps:
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: /ATConfigurations/Dc_PlaybackFlaui/default_site.json
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"

  fw-upgrade:  
    runs-on: windows-latest
    strategy:
      matrix:
        run: ['run1','run2']
    steps:
      - run: echo Run ${{matrix.run}}
      - run: date
      
  
