name: Firmware Upgrade
on: push
#  schedule:
#    - cron: '0 0 * * SAT'

jobs:

  read-json-at-configs:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: get Dc_PlaybackFlaui site
      id: siteDc_PlaybackFlaui
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: ./ATConfigurations/GHActionFwUpgradeConfig.json
          prop_path: 'Dc_PlaybackFlaui.site'
          
    - name: Run echo Dc_PlaybackFlaui site
      run: echo ${{steps.siteDc_PlaybackFlaui.outputs.prop}} 
      
    - name: get FlaUI_PreviewCUC site 
      id: siteFlaUI_PreviewCUC
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: ./ATConfigurations/GHActionFwUpgradeConfig.json
          prop_path: 'FlaUI_PreviewCUC.site'
          
    - name: Run echo FlaUI_PreviewCUC site
      run: echo ${{steps.siteFlaUI_PreviewCUC.outputs.prop}} 



 #   - name: Read default_site.json
  #    id: defaultSite
   #   uses: juliangruber/read-file-action@v1
    #  with:
     #   path: ./ATConfigurations/Dc_PlaybackFlaui/default_site.json
    
    #- name: Echo default_site.json
     # run: echo "${{ steps.defaultSite.outputs.content }}"
      



   # - name: Read run_settings.json
   #   id: runSettings
   #   uses: juliangruber/read-file-action@v1
   #   with:
   #     path: ./ATConfigurations/Dc_PlaybackFlaui/run_settings.json
    
   # - name: Echo run_settings.json
   #   run: echo "${{ steps.runSettings.outputs.content }}"

   # - name: Echo run_settings_users
   #   run: echo "${{ steps.runSettings.outputs.content }}"






#  fw-upgrade:  
 #   needs: read-json-at-configs
  #  runs-on: windows-latest
   # strategy:
    #  matrix:
     #   run: ['run1','run2']
   # steps:
    #  - run: echo Run ${{matrix.run}}
    #  - run: date
      
  
