name: bnetAPI
on: push
env:
  ACCOUNT_REGION: eu
  GAMER_TAG: Brodde#2647
jobs:
  authenticate-bnet:
    runs-on: windows-latest
    outputs:
      access-token: ${{steps.bnet-auth.outputs.access-token}}
      matrix: ${{ steps.fetch-characters.outputs.matrix }}
    steps:

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}} ${{env.ACCOUNT_REGION}}
          echo "::set-output name=access-token::$AccessToken"
  
      - name: Get Characters from Server
        id: fetch-characters
        run: |
          $Characters = ./Scripts/GetCharactersFromServer.ps1 ${{steps.bnet-auth.outputs.access-token }} ${{env.ACCOUNT_REGION}} ${{env.GAMER_TAG}}
          Write-Host $Characters
          echo "::set-output name=matrix::$Characters"

  wire-character-data:
    needs: authenticate-bnet
    runs-on: windows-latest
    strategy:
      matrix: ${{fromJson(needs.authenticate-bnet.outputs.matrix)}}
    outputs:
      character-json: ${{ steps.clean-character-data.outputs.character }}
    steps:
        
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Clean Character Data
        id: clean-character-data
        run: |
          $CharacterData = ./Scripts/WireCharacterData.ps1 ${{env.ACCOUNT_REGION}} ${{env.GAMER_TAG}} ${{needs.authenticate-bnet.outputs.access-token }} ${{ matrix.Id }} ${{ matrix.ClassSlug }}
          echo "::set-output name=matrix::$CharacterData"

  process-character-data:
    needs: wire-character-data
    runs-on: windows-latest
    steps:
      - name: Print json
        run: | 
          $Json = ${{needs.wire-character-data.outputs.character-json}}
          Write-Host $Json