name: bnetAPI
on: push
env:
  ACCOUNT_REGION: eu
  GAMER_TAG: Brodde#2647
jobs:
  authenticate-bnet:
    runs-on: windows-latest
    outputs:
      access-token: ${{steps.bnet-auth.outputs.access-token}}
      matrix: ${{ steps.fetch-characters.outputs.matrix }}
    steps:

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}} ${{env.ACCOUNT_REGION}}
          echo "::set-output name=access-token::$AccessToken"
  
      - name: Get Characters from Server
        id: fetch-characters
        run: |
          $Characters = ./Scripts/GetCharactersFromServer.ps1 ${{steps.bnet-auth.outputs.access-token }} ${{env.ACCOUNT_REGION}} ${{env.GAMER_TAG}}
          Write-Host $Characters
          echo "::set-output name=matrix::$Characters"

  wire-character-data:
    needs: authenticate-bnet
    runs-on: windows-latest
    strategy:
      matrix: ${{fromJson(needs.authenticate-bnet.outputs.matrix)}}
      fail-fast: false
    outputs:
      file-path: ${{ steps.clean-character-data.outputs.file-path }}
      file-name: ${{ steps.clean-character-data.outputs.file-name }}
    steps:
        
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Clean Character Data
        id: clean-character-data
        shell: pwsh
        run: |
          $CharacterDataJson = ./Scripts/WireCharacterData.ps1 ${{env.ACCOUNT_REGION}} ${{env.GAMER_TAG}} ${{needs.authenticate-bnet.outputs.access-token }} ${{ matrix.Id }} ${{ matrix.ClassSlug }}
          $CharacterData = ConvertFrom-Json -InputObject $CharacterDataJson
         
          pwd
          mkdir artifacts/characters
          $CurrentDir = Get-Location
          $FilePath = $CurrentDir.ToString()+"/artifacts/characters/"
          $FileName = $FilePath+$CharacterData.Name+"_"+$CharacterData.Id+".json"
          Write-Host "Path: $FilePath"
          $CharacterData | ConvertTo-Json | Out-File $FileName
          dir artifacts/characters

          echo "::set-output name=file-path::$FilePath"
          echo "::set-output name=file-name::$FileName"
          
      - run: |
            $FilePath = ${{ steps.clean-character-data.outputs.file-path }}
            $FileName = ${{ steps.clean-character-data.outputs.file-name }}
            Write-Host "filePath: $FilePath"
            Write-Host "fileName: $FileName"

      - name: Upload Character Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ steps.clean-character-data.outputs.file-name }}



 # process-character-data:
 #   needs: wire-character-data
 #   runs-on: windows-latest
 #   steps:
 #     - name: Process character Data
 #       run: |
  process-character-data:
    needs: wire-character-data
    runs-on: windows-latest
    steps:
      - name: Process character Data
        run: |
          pwd
          dir ${{needs.wire-character-data.outputs.file-path}}
      