
name: BNet API Training
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  ACCOUNT_REGION: eu
  GAMER_TAG: Brodde#2647
jobs:
  authenticate-bnet:
    runs-on: windows-latest
    outputs:
      access-token: ${{steps.bnet-auth.outputs.access-token}}
      matrix: ${{steps.get-characters.outputs.matrix}}
    steps:
    
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}} ${{env.ACCOUNT_REGION}}
          echo "::set-output name=access-token::$AccessToken"
          
      - name: Get Characters from Server
        id: get-characters
        run: |
          $Characters = ./Scripts/GetCharactersFromServer.ps1 ${{steps.bnet-auth.outputs.access-token }} ${{env.ACCOUNT_REGION}} ${{env.GAMER_TAG}}
          Write-Host $Characters
          echo "::set-output name=matrix::[{\"Id\":134165191,\"ClassSlug\":\"crusader\"},{\"Id\":136750066,\"ClassSlug\":\"barbarian\"}]"
      
      - name: Check matrix
        run: Write-Host ${{steps.get-characters.outputs.matrix }}

  process-charactes:
    needs: authenticate-bnet
    runs-on: windows-latest
    strategy:
      matrix: ${{fromJson(needs.authenticate-bnet.outputs.matrix)}}
    steps:
      - name: Check Matrix Values
        run: |
          Write-Host ${{matrix.Id}}
          Write-Host ${{matrix.ClassSlug}}
          

          
