name: ACA Firmware Upgrade

on: push
    #schedule:
    #    - cron: '0 0 * * 6'

jobs:
  get-devices-to-upgrade:
    name: Get devices to upgrade
    runs-on: windows-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
            
      - run: |
          ./Scripts/GetDevices.ps1
      
      - name: Upload Device info
        uses: actions/upload-artifact@v2
        with:
          name: deviceInfo
          path: deviceInfo.json
                

  upgrade-devices:
    name: Upgrade Devices
    needs: get-devices-to-upgrade
    runs-on: windows-latest
    steps:
      - name: Download deviceInfo artifact
        uses: actions/download-artifact@v2
        with:
          name: deviceInfo
      
      - run: |
          fileName='deviceInfo.json'
          ./Scripts/UpgradeDevice.ps1 "${fileName}"
      