name: ACA Firmware Upgrade

on: push
    #schedule:
    #    - cron: '0 0 * * 6'

jobs:
  get-devices-to-upgrade:
    name: Get devices to upgrade
    runs-on: windows-latest
    steps:
      - name: Get Devices
        shell: pwsh
        run: |
          ./Scripts/GetDevices.ps1
      - name: Upload Device info
        uses: actions/upload-artifact@v2
        with:
          name: deviceInfo
          path: /Scripts/devices/deviceInfo.json

  upgrade-devices:
    name: Upgrade Devices
    needs: get-devices-to-upgrade
    runs-on: windows-latest
    steps:
      - name: Download deviceInfo artifact
        uses: actions/download-artifact@v2
        with:
          name: deviceInfo
      
      - name: Upgrade devices
        shell: pwsh
        run: |
          value=`cat deviceInfo.json`
          ./Scripts/UpgradeDevice.ps1 value
      