
name: Firmware Upgrade
on:  
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  #workflow_dispatch:
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  upgrade-firmware:
    runs-on: windows-latest
    strategy:
      matrix: 
        atConfigurations: ["Test_AtConfiguration_2", "Test_AtConfiguration_2"]

    steps:
    
      - name: Check out repo
        uses: actions/checkout@v2

      - name: get default_site.site
        id: site
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/${{matrix.atConfigurations}}/default_site.json'
            prop_path: 'name'
     
      - name: get run_settings.defaultUser.userName
        id: userName
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/${{matrix.atConfigurations}}/run_settings.json'
            prop_path: 'users.defaultUser.userName'
      
      - name: get run_settings.defaultUser.userPassword
        id: userPassword
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/${{matrix.atConfigurations}}/run_settings.json'
            prop_path: 'users.defaultUser.userPassword'
            
      - name: Print JSon data
        run: echo 
          ${{matrix.atConfigurations}} 
          ${{steps.site.outputs.prop}} 
          ${{steps.userName.outputs.prop}} 
          ${{steps.userPassword.outputs.prop}} 
          
      - name: Run FW Script
        run: |
          ./Scripts/UpgradeFirmware.ps1 ${{matrix.atConfigurations}} ${{steps.site.outputs.prop}} ${{steps.userName.outputs.prop}} ${{steps.userPassword.outputs.prop}} 
          
          
          
          
          
        
