
name: Firmware Upgrade
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  upgrade-firmware:
    runs-on: windows-latest
    strategy:
      matrix: 
        atConfigurations: ["Dc_PlaybackFlaui","Dc_RecordFlaui"]

    steps:    
      - uses: actions/checkout@v2
      
      - name: Swow atConfiguration
        run: echo ${{matrix.atConfigurations}}

        #read config json site name
      - name: get default_site.site
        id: site
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/Dc_PlaybackFlaui/default_site.json'
            prop_path: 'name'
      - run: echo ${{steps.site.outputs.prop}} 

        #read config json credentials

        # run ps1 script with json data

        
