
name: Firmware Upgrade
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  upgrade-firmware:
    runs-on: windows-latest
    strategy:
      matrix: 
        atConfigurations: ["Dc_PlaybackFlaui","Dc_RecordFlaui", "FlaUI_PreviewCUC"]

    steps:    
      - uses: actions/checkout@v2
      
      - name: Swow atConfiguration
        run: echo ${{matrix.atConfigurations}}

      - name: get default_site.site
        id: site
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/${{matrix.atConfigurations}}/default_site.json'
            prop_path: 'name'
      - run: echo ${{steps.site.outputs.prop}} 

      - name: get run_settings.defaultUser.userName
        id: userName
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/${{matrix.atConfigurations}}/run_settings.json'
            prop_path: 'users.defaultUser.userName'
      - run: echo ${{steps.userName.outputs.prop}} 
      
      - name: get run_settings.defaultUser.userPassword
        id: userPassword
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './ATConfigurations/${{matrix.atConfigurations}}/run_settings.json'
            prop_path: 'users.defaultUser.userPassword'
      - run: echo ${{steps.userPassword.outputs.prop}} 
        

        # run ps1 script with json data

        
