name: "Scheduled pws script runner"
on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run SecondScript        
        uses: actions/checkout@v2
      - run: |
          ./Scripts/SecondScript.ps1
