name: "Close stale issues"
on:
  schedule:
  - cron: "0/5 * * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./Scripts/SecondScript.ps1