
name: WOW API TRAINING
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  authenticate-bnet:
    runs-on: windows-latest
    steps:
    
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
       
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}}
          Write-Host "accToken $AccessToken"
          echo ::set-output name=access-token::$(echo ${AccessToken}
      
      - name: Get Characters from Server
        with:
          args: ${{ steps.bnet-auth.outputs.access-token }}
        run: |
          $AccessToken = ${{env.action_state}}
          Write-Host "accToken $AccessToken"
          Write-Host "args $args"
          Write-Host "args2 ${{args}}"

          
