
name: WOW API TRAINING
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  authenticate-bnet:
    runs-on: windows-latest
    steps:
    
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
       
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}}
          Write-Host "accToken $AccessToken"
          echo "action_state=$AccessToken" >> $GITHUB_ENV
      
      - name: Get Characters from Server
        run: |
          $AccessToken = ${{env.action_state}}
          Write-Host $AccessToken

          
