
name: WOW API TRAINING
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  authenticate-bnet:
    runs-on: windows-latest
    steps:
    
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}}
          echo '::set-output name=access-token::${{AccessToken}}'

      - name: Get Characters from Server
        run: |
          $AccessToken = ${{steps.bnet-auth.outputs.access-token}}
          Write-Host $AccessToken