
name: WOW API TRAINING
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  authenticate-bnet:
    runs-on: windows-latest
    outputs:
      access-token: ${{steps.bnet-auth.outputs.access-token}}
      access-token2: ${{steps.bnet-auth.outputs.access-token2}}
      access-token3: ${{steps.bnet-auth.outputs.access-token3}}
    steps:
    
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Authenticate with BNet
        id: bnet-auth
        run: |
       
          $AccessToken =  ./Scripts/GetBnetToken.ps1 ${{secrets.WOW_CLIENT_ID}} ${{secrets.WOW_CLIENT_SECRET}}
          Write-Host "accToken $AccessToken"
          echo "::set-output name=access-token::$(echo ${AccessToken})"
          echo "::set-output name=access-token2::$AccessToken"
          echo "::set-output name=access-token3::BAJS"
      
      - name: Get Characters from Server
        run: |
          $AccessToken = ${{ steps.bnet-auth.outputs.access-token }}
          Write-Host "accToken $AccessToken"

          $AccessToken2 = ${{ steps.bnet-auth.outputs.access-token2 }}
          Write-Host "accToken2 $AccessToken2"

          $AccessToken3 = ${{ steps.bnet-auth.outputs.access-token3 }}
          Write-Host "accToken3 $AccessToken3"

          
